#!/bin/tcsh

if ($#argv < 5) then
    echo "Usage: NODDI_g <ficvf_name.mnc> <fiso_name.mnc> <f_name.mnc> <out_base> <scale_factor> <mask_name.mnc>"
exit
endif


minccalc -float -expression "clamp(A[0]*(1-A[1])*(1-$5*A[2]),0,1)" $1 $2 $3 $4_avf_unmasked.mnc -nocheck_dimensions

minccalc -float -expression "clamp($5*A[0],0,1)" $3 $4_mvf_unmasked.mnc -nocheck_dimensions

minccalc -float -expression "clamp(sqrt(1/(1+A[0]/A[1])),0,1)" $4_mvf_unmasked.mnc $4_avf_unmasked.mnc $4_g_unmasked.mnc -nocheck_dimensions

if ($#argv == 6) then
    mincmath -float -mult $4_avf_unmasked.mnc $6 $4_avf.mnc -nocheck_dimensions
    mincmath -float -mult $4_mvf_unmasked.mnc $6 $4_mvf.mnc -nocheck_dimensions
    mincmath -float -mult $4_g_unmasked.mnc $6 $4_g.mnc -nocheck_dimensions
    rm -f $4_mvf_unmasked.mnc $4_avf_unmasked.mnc $4_g_unmasked.mnc
endif


